# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"  # Exemple avec l'écosystème npm (Node.js)
    directory: "/"            # Emplacement des manifestes de paquets (racine du projet)
    schedule:
      interval: "weekly"       # Fréquence des mises à jour (chaque semaine)
